### ISSUE TITLE
Data Validation needed on Peers received from tracker

### ISSUE THREAD

**Issue by kill-9-me** [mono/monotorrent#26]
A peer without a port from the tracker results in the following exception. This can and does routinely happen. Especially on open source torrents (IE: Ubuntu)

System.ArgumentOutOfRangeException was unhandled by user code
  HResult=-2146233086
  Message=Specified argument was out of the range of valid values.
Parameter name: port
  Source=System
  ParamName=port
  StackTrace:
       at System.Net.IPEndPoint..ctor(IPAddress address, Int32 port)
       at MonoTorrent.Client.Connections.IPV4Connection..ctor(Uri uri) in c:\Users\xxx\Documents\GitHub\xxx\MonoTorrent\MonoTorrent.Client\PeerConnections\TCPConnection.cs:line 83
  InnerException:

**Comment by alanmcgovern** [comment]
sounds good to me!
